name: Lighthouse CI Audit

on:
  push:
    branches:
      - optimized
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout optimized branch
        uses: actions/checkout@v4
        with:
          ref: optimized

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Lighthouse and dependencies
        run: |
          npm install -g @lhci/cli lighthouse jq bc

      - name: Start local PHP server
        run: |
          php -S localhost:8080 -t . > /dev/null 2>&1 &
          sleep 5

      - name: Run Lighthouse CI
        run: |
          lhci collect --url=http://localhost:8080/index.php
          lhci collect --url=http://localhost:8080/about.php
          lhci collect --url=http://localhost:8080/contact.php
          lhci assert --assertions.performance=90

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci
