name: Lighthouse CI

on:
  push:
    branches:
      - optimized   # run only on optimized branch
  workflow_dispatch: # allow manual trigger

jobs:
  lhci:
    name: Run Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Build site
        run: |
          # Replace with your build command if needed (npm run build, hugo, etc.)
          # If it's static HTML, skip build and just use current files
          echo "No build step required."

      - name: Run Lighthouse CI
        run: |
          lhci autorun --collect.url="https://<your-github-username>.github.io/<repo-name>/"
