name: Website Optimization & Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js (use v16 for Squoosh WASM compatibility)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # 3. Install dependencies for optimization
      - name: Install Optimization Tools
        run: |
          npm install -g html-minifier-terser clean-css-cli terser \
          purgecss @squoosh/cli@0.7.1 cheerio @lhci/cli

      # 4. Optimize HTML files
      - name: Minify HTML
        run: |
          shopt -s nullglob
          find . \( -name "*.html" -o -name "*.php" \) | while read -r file; do
            html-minifier-terser --collapse-whitespace --remove-comments \
              --minify-js true --minify-css true \
              --input-dir "$(dirname "$file")" \
              --output-dir "$(dirname "$file")" \
              --file-ext html,php
          done

      # 5. Optimize CSS (remove unused Bootstrap + custom CSS)
      - name: Purge & Minify CSS
        run: |
          shopt -s nullglob
          if [ -d css ]; then
            find css -name "*.css" | while read -r file; do
              purgecss --css "$file" --content "**/*.php" "**/*.html" "**/*.js" \
                --output css
              cleancss -o "$file" "$file"
            done
          fi

      # 6. Minify JS
      - name: Minify JS
        run: |
          shopt -s nullglob
          if [ -d js ]; then
            find js -name "*.js" | while read -r file; do
              terser "$file" -o "$file" --compress --mangle
            done
          fi

      # 7. Convert & compress images (WebP & AVIF)
      - name: Optimize Images
        run: |
          mkdir -p optimized_images
          find images -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | while read -r img; do
            rel_path="${img#images/}"
            rel_dir=$(dirname "$rel_path")
            mkdir -p "optimized_images/$rel_dir"
            npx @squoosh/cli --webp '{"quality":80}' --avif '{"quality":60}' "$img" -d "optimized_images/$rel_dir"
          done

          # Overwrite originals with optimized images
          rsync -a optimized_images/ images/

      # 8. Add lazy loading to <img> tags
      - name: Add Lazy Loading
        run: |
          find . \( -name "*.html" -o -name "*.php" \) | while read -r file; do
            node -e "
              const fs = require('fs');
              const cheerio = require('cheerio');
              let html = fs.readFileSync('$file', 'utf8');
              const $ = cheerio.load(html);
              $('img').each((_, el) => {
                if (!$(el).attr('loading')) $(el).attr('loading', 'lazy');
              });
              fs.writeFileSync('$file', $.html());
            "
          done

      # 9. Generate Responsive Images
      - name: Generate Responsive Images
        run: |
          find images -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | while read -r img; do
            rel_path="${img#images/}"
            rel_dir=$(dirname "$rel_path")
            for size in 320 640 1024; do
              mkdir -p "images/$rel_dir/${size}w"
              npx @squoosh/cli --resize "{\"width\":$size}" "$img" -d "images/$rel_dir/${size}w"
            done
          done

      # 10. Run Lighthouse on all pages
      - name: Lighthouse CI
        run: |
          lhci autorun --collect.url="http://localhost/index.php" \
                       --collect.url="http://localhost/about.php" \
                       --collect.url="http://localhost/contact.php"

      # 11. Fail if performance < 90
      - name: Check Lighthouse Performance
        run: |
          SCORE=$(grep -m1 '"performance"' .lighthouseci/manifest.json | grep -o '[0-9]*')
          if [ "$SCORE" -lt 90 ]; then
            echo "Performance score $SCORE < 90. Failing."
            exit 1
          fi

      # 12. Push to optimized branch
      - name: Push to optimized branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B optimized
          git add .
          git commit -m "Optimized site" || echo "No changes to commit"
          git push origin optimized --force
