name: Website Optimization

on:
  push:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Optimization Tools
        run: |
          npm install -g html-minifier-terser clean-css-cli terser purgecss @squoosh/cli cheerio

      - name: Minify HTML (including PHP)
        run: |
          find . \( -iname "*.html" -o -iname "*.php" \) | while read -r file; do
            html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true \
              --input-dir "$(dirname "$file")" --output-dir "$(dirname "$file")" --file-ext html,php
          done

      - name: Purge & Minify CSS
        run: |
          if [ -d css ]; then
            find css -iname "*.css" | while read -r file; do
              purgecss --css "$file" --content "**/*.php" "**/*.html" "**/*.js" --output css
              cleancss -o "$file" "$file"
            done
          fi

      - name: Minify JS
        run: |
          if [ -d js ]; then
            find js -iname "*.js" | while read -r file; do
              terser "$file" -o "$file" --compress --mangle
            done
          fi

      - name: Optimize Images (WebP & AVIF)
        run: |
          mkdir -p optimized_images
          find images -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | while read -r img; do
            rel_path="${img#images/}"
            rel_dir=$(dirname "$rel_path")
            mkdir -p "optimized_images/$rel_dir"
            npx @squoosh/cli --webp '{"quality":80}' --avif '{"quality":60}' "$img" -d "optimized_images/$rel_dir"
          done
          rsync -a optimized_images/ images/

      - name: Generate Responsive Images (320, 640, 1024 widths)
        run: |
          find images -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | while read -r img; do
            rel_path="${img#images/}"
            rel_dir=$(dirname "$rel_path")
            for size in 320 640 1024; do
              mkdir -p "images/$rel_dir/${size}w"
              npx @squoosh/cli --resize "{\"width\":$size}" "$img" -d "images/$rel_dir/${size}w"
            done
          done

      - name: Add Lazy Loading to Images
        run: |
          find . \( -iname "*.html" -o -iname "*.php" \) | while read -r file; do
            node -e "
              const fs = require('fs');
              const cheerio = require('cheerio');
              let html = fs.readFileSync('$file', 'utf8');
              const $ = cheerio.load(html);
              $('img').each((_, el) => {
                if (!$(el).attr('loading')) $(el).attr('loading', 'lazy');
              });
              fs.writeFileSync('$file', $.html());
            "
          done

      # NOTE: Automatic removal of unused images is complex and not included here.
      # Consider using tools like 'webpack', 'gulp', or manual cleanup for that.

      - name: Push to optimized branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -B optimized
          git add .
          git commit -m "Optimized site" || echo "No changes to commit"
          git push origin optimized --force
